version: "3.3"
services:
  db:
    build:
      dockerfile: ./db-dockerfile
      context: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  node-tests:
    build: .
    environment:
      - DatabaseHost=db
    depends_on:
      - db
